//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ZLUseDevManage.rc
//
#define ID_DEF_PARAM                    3
#define ID_START_SEARCH                 3
#define ID_PARAM_EDIT                   4
#define ID_RESTART_DEV                  4
#define ID_DEV_OPEN                     5
#define ID_ABOUT                        5
#define ID_DEV_CLOSE                    6
#define ID_SAFE_CONNECT                 6
#define ID_DEV_WRITE                    7
#define ID_DEV_READ                     8
#define ID_ADD_IP                       9
#define ID_MANUAL_ADD                   9
#define ID_CLEAR_IP                     10
#define ID_DEV_COMM                     10
#define ID_P2P_MANAGE                   10
#define ID_BROADCAST_COMM               11
#define ID_SEND_TEST                    11
#define ID_IO_CONTROL                   12
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ZLUSEDEVMANAGE_DIALOG       102
#define IDP_SOCKETS_INIT_FAILED         103
#define ZL_STR_NO_DATA_RECV             104
#define IDD_PARAM                       105
#define ZL_STR_CLOSE_BST_OK             105
#define IDD_MANUAL                      106
#define ZL_STR_CLOSE_BST_FAIL           106
#define IDD_DEV_COMM                    107
#define ZL_STR_START_BST_OK             107
#define IDD_P2P_MANAGE                  107
#define IDD_BROADCAST                   108
#define ZL_STR_START_BST_FAIL           108
#define IDD_NEED_KEY                    108
#define ZL_STR_SEND_FAIL                109
#define IDD_IO_CONTROL                  109
#define ZL_STR_OPEN_DEV_OK              110
#define ZL_STR_CLOSE_DEV_OK             111
#define ZL_STR_CLOSE_DEV_FAIL           112
#define ZL_STR_OPEN_DEV_FAIL            113
#define ZL_STR_MANUAL_ADD_OK            114
#define ZL_STR_MANUAL_ADD_FAIL          115
#define IDR_MAINFRAME                   128
#define IDC_DEV_NAME                    1000
#define IDC_DEV_BAUNDRATE               1001
#define IDC_DEV_PARITY                  1002
#define IDC_SEND_TEXT                   1002
#define IDC_DEV_BITNUM                  1003
#define IDC_RECV_TEXT                   1003
#define IDC_DEV_STOPBIT                 1004
#define IDC_MODE_AUTO_RECV              1004
#define IDC_DEV_LOCAL_IP                1005
#define IDC_MODE_MANUAL_RECV            1005
#define IDC_DEV_LOCAL_PORT              1006
#define IDC_MODE_FAST_SEND              1006
#define IDC_DEV_FLOW_CONTROL            1007
#define IDC_MODE_BULK_SEND              1007
#define IDC_DEV_GATEWAY                 1008
#define IDC_MODE_MESSAGE                1008
#define IDC_DEV_NETMASK                 1009
#define IDC_MODE_CALL_BACK              1009
#define IDC_DEV_WORKMODE                1010
#define IDC_DEV_DESTIP                  1011
#define IDC_DNS_SERVER_IP               1011
#define IDC_DEV_DESTPORT                1012
#define IDC_DEV_VIR_COM                 1013
#define IDC_DEV_GAP_TIME                1014
#define IDC_MANUAL_IP                   1014
#define IDC_DEV_PACKING_LEN             1015
#define IDC_MANUAL_PORT                 1015
#define IDC_CONNECT_KEY                 1015
#define IDC_DEV_FRAME_END_BYTE          1016
#define IDC_MANUAL_IP2                  1016
#define IDC_MULTI_HOST_TIME_OUT         1016
#define IDC_DEV_FRAME_START_BYTE        1017
#define IDC_485_HALF_GAP                1017
#define IDC_SEND_DATA                   1017
#define IDC_DEV_IPMODE                  1018
#define IDC_SEND_HEX                    1018
#define IDC_CONNECT_IP                  1018
#define IDC_DEV_DESTMODE                1019
#define IDC_RECV_HEX                    1019
#define IDC_CONNECT_PORT                1019
#define IDC_DEV_APP_PROTOCOL            1020
#define IDC_GET_LOCAL_ADDR              1021
#define IDC_DEST_IP                     1022
#define IDC_DEV_LIST                    1022
#define IDC_KEEP_ALIVE_TIME             1023
#define IDC_BST_LOCAL_PORT              1023
#define IDC_RECONNECT_TIME              1024
#define IDC_BST_DEST_PORT               1024
#define IDC_QUERY_IO                    1024
#define IDC_WEB_PORT                    1025
#define IDC_STATUS_IO0                  1025
#define IDC_UDP_FILTER_POS              1026
#define IDC_STATUS_IO1                  1026
#define IDC_INPUT_KEY                   1026
#define IDC_UDP_FILTER_CODE             1027
#define IDC_STATUS_IO2                  1027
#define IDC_UDP_FILTER_MASK             1028
#define IDC_STATUS_IO3                  1028
#define IDC_DEV_VER                     1029
#define IDC_STATUS_IO4                  1029
#define IDC_FUNC_SEL_WEB_DOWNLOAD       1030
#define IDC_STATUS_IO5                  1030
#define IDC_FUNC_SEL_DNS                1031
#define IDC_STATUS_IO6                  1031
#define IDC_FUNC_SEL_REAL_COM           1032
#define IDC_STATUS_IO7                  1032
#define IDC_FUNC_SEL_MODBUS_TCP         1033
#define IDC_SET1_IO0                    1033
#define IDC_FUNC_SEL_SPR                1034
#define IDC_SET1_IO1                    1034
#define IDC_FUNC_SEL2_P2P               1034
#define IDC_FUNC_SEL_DHCP               1035
#define IDC_SET1_IO2                    1035
#define IDC_FUNC_SEL_UDP_FILTER         1036
#define IDC_SET1_IO3                    1036
#define IDC_ENABLE_P2P                  1036
#define IDC_FUNC_SEL_UNICODE            1037
#define IDC_SET1_IO4                    1037
#define IDC_ENABLE_SEND_MAC             1037
#define IDC_DEV_UDP_GROUP_IP            1038
#define IDC_SET1_IO5                    1038
#define IDC_SET1_IO6                    1039
#define IDC_UDP_MODIFY_NEED_KEY         1039
#define IDC_SET1_IO7                    1040
#define IDC_ENABLE_TCP_NEED_KEY         1040
#define IDC_IO_SUPPORT                  1041
#define IDC_SET0_IO0                    1042
#define IDC_SET0_IO1                    1043
#define IDC_SET0_IO2                    1044
#define IDC_SET0_IO3                    1045
#define IDC_SET0_IO4                    1046
#define IDC_SET0_IO5                    1047
#define IDC_SET0_IO6                    1048
#define IDC_SET0_IO7                    1049
#define IDC_IO_EN                       1050
#define IDC_EDIT1                       1051
#define IDC_P2P_ID                      1051
#define IDC_WIFI_SSID                   1051
#define IDC_EDIT2                       1052
#define IDC_SIMULATE_PORT               1052
#define IDC_WIFI_KEY                    1052
#define IDC_DLL_VER                     1053
#define IDC_P2P_LIST                    1055
#define IDC_P2P_ADD                     1056
#define IDC_P2P_DEL                     1057
#define IDC_P2P_REFRESH                 1058
#define ID_MODIFY_KEY                   1058
#define IDC_OLD_KEY                     1059
#define IDC_NEW_KEY                     1060
#define ID_CONNECT_WITH_KEY             1061
#define IDC_MODIFY_KEY_DEV_ID           1062
#define ID_AUTH_DEV_VALID               1063
#define IDC_WIFI_STA_AP                 1063
#define IDC_WIFI_KEY_TYPE               1064
#define IDC_WIFI_CHANNEL                1066
#define IDC_WIFI_DHCP_SERVER            1067
#define IDC_WIFI_ETH_WIFI_BRIDGE        1068
#define ZL_STR_DEV_STATUS               61205
#define ZL_STR_DEV_NAME                 61206
#define ZL_STR_DEV_IP                   61207
#define ZL_STR_DEV_PORT                 61208
#define ZL_STR_DLL_LOAD_FAIL            61209
#define ZL_STR_DLL_INIT_FAIL            61210
#define ZL_STR_LINKED                   61215
#define ZL_STR_NOT_LINKED               61216
#define ZL_STR_SEL_FIRST                61217
#define ZL_STR_DEV_ID                   61218
#define ZL_STR_DLL_VER_EER              61219

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1064
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
